variables:
  GIT_SUBMODULE_STRATEGY: recursive

image:
  192.168.103.10:443/build_cmake_stm

# build:
#   stage: build
#   script:
#     - mkdir build && cd build
#     - cmake .. -DBUILD_TYPE=S -DSTM_CODE=F103RBTX
#     - make
#   artifacts:
#     paths:
#       - build/

test:
  stage: test
  script:
    - echo Running tests

deploy:
  stage: deploy
  script:
    - apk add git
    - echo "Define your deployment script!"
    - git clone https://piotr.kwiatkowski:$GITHUB_ACCESS_TOKEN@github.com/Pararanta/wallbox-device/ --branch=master
    - cd wallbox-device
    - ls -lah
  environment: production
