variables:
  GIT_SUBMODULE_STRATEGY: recursive

image:
  192.168.103.10:443/build_cmake_stm

# build:
#   stage: build
#   script:
#     - mkdir build && cd build
#     - cmake .. -DBUILD_TYPE=S -DSTM_CODE=F103RBTX
#     - make
#   artifacts:
#     paths:
#       - build/

# test:
#   stage: test
#   script:
#     - echo Running tests

deploy:
  stage: deploy
  script:
    - apk add git
    - echo "Define your deployment script!"
    - git clone https://piotr.kwiatkowski:$GITHUB_ACCESS_TOKEN@github.com/PiotrKwiatkowskiVoitas/glowing-lamp --branch=main
    - ls -lah # add file to repo from base.
    - mv main.cpp glowing-lamp/
    - cd glowing-lamp/
    - git config --global user.email "help@example.com"
    - git config --global user.name "Voitas CICD agent"
    - git remote remove origin
    - git remote add origin https://piotr.kwiatkowski:$GITHUB_ACCESS_TOKEN@github.com/PiotrKwiatkowskiVoitas/glowing-lamp
    - git add -A
    - git commit -m "Added in external CICD"
    - git push
  # Add release
  environment: production
